image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - publish

before_script:
  - npm install

test:
  stage: test
  script:
    - npm run lint

publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - git clone --single-branch --branch custom https://github.com/myin142/plyr.git
    - cd plyr && npm install && npm run build && npm link ../ && cd ../
    - npm run build
    - npm run publish -- --api-key=$AMO_ISSUER --api-secret=$AMO_SECRET
  artifacts:
    paths:
      - ./dist/web-ext-artifacts/*.xpi
