image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - publish

before_script:
  - npm install

build:
  stage: build
  only:
    - master
  script:
    - npm run lint
    - git clone --single-branch --branch custom https://github.com/myin142/plyr.git
    - cd plyr && npm install && npm run build && npm link ../ && cd ../
    - npm run build
    - cd dist/ && npx web-ext sign --api-key=$AMO_ISSUER --api-secret=$AMO_SECRET
  artifacts:
    paths:
      - ./*.xpi

publish:
  stage: publish
  dependencies:
    - build
  only:
    - master
  script:
    - ls -la
    # - web-ext sign --api-key=$AMO_ISSUER --api-secret=$AMO_SECRET
