language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

script:
  - npm run lint
  - git clone https://github.com/myin142/plyr.git
  - cd plyr && npm install && npm run build && npm link ../ && cd ../
  - npm run build

before_deploy:
  - cd dist/ && zip -r release.zip *

deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_KEY"
  file: "release.zip"
  skip_cleanup: true
  on:
    tags: true