language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

script:
  - npm run lint
  - npm run build

deploy:
  providers: releases
  script: ls
  api_key: "$GITHUB_RELEASE_KEY"
  file: ""
  skip_cleanup: true
  on:
    tags: true