language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

script:
  - npm run lint
  - npm run build

before_deploy:
  - cd dist/ && zip -r release.zip *

deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_KEY"
  file: "./dist/release.zip"
  skip_cleanup: true
  on:
    tags: true